# Generated by Django 4.2.4 on 2023-08-08 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('previous_price', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('product_price', models.FloatField()),
                ('is_in_main_page', models.BooleanField(default=False)),
                ('product_image', models.ImageField(upload_to='products/')),
                ('product_status', models.CharField(choices=[('1', 'available'), ('2', 'out of stock'), ('3', 'top selling')], max_length=20)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='App_Shop.productcategory')),
            ],
        ),
    ]
