# Generated by Django 4.2.4 on 2023-08-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0002_alter_products_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='unit_status',
            field=models.CharField(blank=True, choices=[('1', 'kg'), ('2', 'pcs'), ('3', 'dozon'), ('4', 'litter')], max_length=20, null=True),
        ),
    ]
