# Generated by Django 4.2.4 on 2023-08-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0003_products_product_description_products_unit_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='min_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
