# Generated by Django 4.2.4 on 2023-08-08 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0004_products_min_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='unit_status',
            field=models.CharField(blank=True, choices=[('kg', 'kg'), ('pcs', 'pcs'), ('dozon', 'dozon'), ('litter', 'litter')], max_length=20, null=True),
        ),
    ]
