# Generated by Django 4.2.4 on 2023-08-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0005_alter_products_unit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_status',
            field=models.CharField(choices=[('available', 'available'), ('out of stock', 'out of stock'), ('top selling', 'top selling')], max_length=20),
        ),
    ]
