# Generated by Django 4.2.4 on 2023-08-26 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0009_alter_productcategory_options_alter_products_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
