# Generated by Django 4.2.4 on 2023-08-27 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Shop', '0010_remove_orderitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
